### ISSUE TITLE
Blender scene manager 

### ISSUE THREAD

**Issue by SushilRagoonath** [zaklaus/NEON86#10]
Hi,
trying to use the blender scene manager in 2.91, I see no NEON86 option under the views button in the 3d view. Is there a special way to install or run it?
( now trying 2.90.1 but still nothing )

**Comment by zpl-zak** [comment]
Hi, I'll have a look at it, it could be that the addon is outdated.

**Comment by zpl-zak** [comment]
Not sure what's up, this is what I get on Blender 3.2.1 
![image](https://user-images.githubusercontent.com/9026786/179159999-ca91b09e-a196-4907-aefa-94c6e869fa36.png)

I have downloaded the scene_manager.py file and installed it in addon manager.

**Comment by SushilRagoonath** [comment]
Thanks, I was just looking in the wrong place.
